-- DROP previous instance of table AUTHOR
DROP TABLE AUTHOR;

-- Create AUTHOR
CREATE TABLE AUTHOR 
(
    AUTHOR_NUM DECIMAL(2,0) PRIMARY KEY,
    AUTHOR_LAST CHAR(12),
    AUTHOR_FIRST CHAR(10)
);

INSERT INTO AUTHOR VALUES (1,'Morrison','Toni');
INSERT INTO AUTHOR VALUES (2,'Solotaroff','Paul');
INSERT INTO AUTHOR VALUES (3,'Vintage','Vernor');
INSERT INTO AUTHOR VALUES (4,'Francis','Dick');
INSERT INTO AUTHOR VALUES (5,'Straub','Peter');


--SELECT * FROM AUTHOR;
--SELECT AUTHOR_NUM, AUTHOR_LAST FROM AUTHOR;


DROP TABLE DEPT;

CREATE TABLE DEPT
(
    DEPTNO NUMBER(2) PRIMARY KEY
    ,DNAME VARCHAR2(14)
   ,LOC VARCHAR2(13) 
);


INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');


DROP TABLE EMP;
CREATE TABLE EMP
 (
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7, 2),
    COMM NUMBER(7, 2),
    DEPTNO NUMBER(2) REFERENCES DEPT(DEPTNO)    
);

INSERT INTO EMP VALUES
 (7369, 'SMITH', 'CLERK', 7902,
 TO_DATE('17-DEC-1980', 'DD-MON-YYYY'), 800, NULL, 20);
INSERT INTO EMP VALUES
 (7499, 'ALLEN', 'SALESMAN', 7698,
 TO_DATE('20-FEB-1981', 'DD-MON-YYYY'), 1600, 300, 30);
INSERT INTO EMP VALUES
 (7521, 'WARD', 'SALESMAN', 7698,
 TO_DATE('22-FEB-1981', 'DD-MON-YYYY'),
1250, 500, 30);
INSERT INTO EMP VALUES
 (7566, 'JONES', 'MANAGER', 7839,
 TO_DATE('2-APR-1981', 'DD-MON-YYYY'), 2975, NULL, 20);
INSERT INTO EMP VALUES
 (7654, 'MARTIN', 'SALESMAN', 7698,
 TO_DATE('28-SEP-1981', 'DD-MON-YYYY'), 1250, 1400, 30);
INSERT INTO EMP VALUES
 (7782, 'CLARK', 'MANAGER', 7839,
 TO_DATE('9-JUN-1981', 'DD-MON-YYYY'), 2450, NULL, 10);
INSERT INTO EMP VALUES
 (7839, 'KING', 'PRESIDENT', NULL,
 TO_DATE('17-NOV-1981', 'DD-MON-YYYY'), 5000, NULL, 10);
 
 
 SELECT ename, job FROM emp;
 
--SELECT ename, job, hiredate FROM emp
--WHERE deptno = 30 ORDER BY hiredate;

--SELECT deptno, dname FROM dept;

SELECT 
    ename, dname, loc
FROM
    emp, dept
WHERE
    emp.deptno = dept.deptno;

 